package com.project.webservice.entities.emun;

public enum Medicament {
    ANALGESIC,
    ANTIBIOTIC,
    ANTI_INFLAMMATORY,
    ANTIPYRETIC,
    ANTIVIRAL,
    ANTIFUNGAL,
    ANTIHISTAMINE,
    ANTICOAGULANT,
    ANTACID,
    ANTICONVULSANT,
    ANTIEMETIC,
    ANTIDEPRESSANT,
    ANXIOLYTIC,
    DECONGESTANT,
    DIURETIC,
    LAXATIVE,
    ANTIHYPERTENSIVE,
    HORMONE_THERAPY,
    IMMUNOSUPPRESSANT,
    MUSCLE_RELAXANT,
    SEDATIVE,
    STEROID,
    VITAMIN_SUPPLEMENT;
}
