package com.project.webservice.entities.emun;

public enum SpecialiteMedicale {
    MEDECINE_GENERALE,
    CARDIOLOGIE,
    DERMATOLOGIE,
    PEDIATRIE,
    GYNECOLOGIE,
    CHIRURGIE_GENERALE,
    NEUROLOGIE,
    OPHTALMOLOGIE,
    ORTHOPEDIE,
    PSYCHIATRIE,
    RADIOLOGIE,
    UROLOGIE,
    OTO_RHINO_LARYNGOLOGIE,
    ENDOCRINOLOGIE,
    ONCOLOGIE,
    NEPHROLOGIE,
    RHUMATOLOGIE,
    PNEUMOLOGIE,
    INFECTIOLOGIE,
    MEDECINE_DU_TRAVAIL
}

